### PR TITLE
chore: remove @cypress/schematic from cli.schematicCollections in angular.json

### LINKED ISSUE #12: remove @cypress/schematic from cli.schematicCollections in angular.json
Currently, we wanna create jasmine test file on ng generate component command, but cypress test is created because @cypress/schematic is in `angular.json`. I think we should remove `"@cypress/schematic", ` from there.

```json
  "cli": {
    "schematicCollections": ["@cypress/schematic", "@angular-eslint/schematics", "@schematics/angular"]
  }
}

```

### PR DESCRIPTION
**Pull request by kobakaku**
close #12

### CODE REVIEW

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
@kobakaku 
Fixed source code is OK.
I recommend to comment `close #12` on this pull request to automate issue handling. ( #12  is issue number)
Please add a comment above.
After you add the comment to this pull request, I will approve.
Thank you.

**Comment by kobakaku** [comment]
@YasunoriMATSUOKA 
I changed the commit message.
How is that?

**Comment by YasunoriMATSUOKA** [comment]
I mean the following comment on this pull request. (not commit message)

close #12 

If this pull request contains the comment above, then, this pull request is related to the issue, and, when this pull request merge, the #12 issue is closed automatically.
With that comment, we can manage issues efficiently.
Does it make sense?

**Comment by kobakaku** [comment]
@YasunoriMATSUOKA 
okay!
I understand it.

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
