### PR TITLE
feat: firebase functions base implementation

### PR DESCRIPTION
**Pull request by kobakaku**
I emulated on local development and push [Add user] of Authentification on the window.

The image below is outputed then.
`v1.auth.onCreate` and `v1.firestore.user.onCreate` did work correctly, but I don't know why `v1.https.onCall.v1.auth.onCreate` and `v1.https.onCall.v1.firestore.user.onCreate` did mistakenly work .
And, I couldn't solve the error of `Your function was killed because it raised an unhandled error.`

If you know the solution, please tell me.

スクリーンショット 2023-02-21 19 22 10

### CODE REVIEW

**Comment by kobakaku** [comment]
Even though I didn't fix at all, it worked correctly without the error on my local environment now .

**Comment by kobakaku** [comment]
> now

**Comment by kobakaku** [comment]
I installed "type-predicates-generator@0.3.2".
Please check it .

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
