### PR TITLE
feat: github actions

### PR DESCRIPTION
**Pull request by kobakaku**

### CODE REVIEW

**Comment by kobakaku** [comment]
You can see some check didn't go through. 

I don't know why that is caused in detail.
but it seems the content of "package-lock.json" is different from one of your web-app-hands-on directory.

I will search the cause.

**Comment by YasunoriMATSUOKA** [comment]
@kobakaku 
I think we can fix this ci error with the following procedure. The cause of error seems to be missmatch of `package-lock.json`'s lockfileVersion. Current package-lock.json's lockfileVersion is 3, but Node.js 14.x and npm 6.x does not seem to be able to support it.

1. remove current package-lock.json
2. set your node version to node@16 with volta cli
3. set your npm version to npm@bundled with volta cli -> npm@8
4. execute `npm install`
6. push the change

**Comment by YasunoriMATSUOKA** [comment]
@kobakaku 
Another error seems to occur...
I guess this problem will occur in only Node.js 14.x.
I think Node.js 14 is not essential, so please fix github actions related yml files to remove Node.js 14.x CI.
Thank you.

**Comment by kobakaku** [comment]
I executed `npm install` with 16.19.0 version of node and 8.19.3 version of npm.
Afterthat, I got an error below on Gthub Actions.
`npm ERR! @esbuild/android-arm not accessible from esbuild`.

**Comment by YasunoriMATSUOKA** [comment]
https://github.com/next-web-technology/symbol-social-wallet/pull/13#issuecomment-1426998276

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
